---
name: cross_fit
description: A crossfit Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.19.2 <3.0.0"
dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.7.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.3
  get_it: ^7.2.0
  hexcolor: ^3.0.1
  page_transition: ^2.0.9
  progress_state_button: ^1.0.4
  rounded_loading_button: ^2.1.0
  shimmer: ^2.0.0
  syncfusion_flutter_charts: ^20.4.53
  syncfusion_flutter_gauges: ^20.4.53

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
    - family: CrossFitIcons
      fonts:
        - asset: assets/icons/CrossFitIcons.ttf
