/// Flutter icons CrossFitIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CrossFitIcons
///      fonts:
///       - asset: fonts/CrossFitIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CrossFitIcons {
  CrossFitIcons._();

  static const _kFontFam = 'CrossFitIcons';
  static const String? _kFontPkg = null;

  static const IconData workout = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData endurance = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meal = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strength = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
